# prompt> ansible-playbook build_docker_image.yml -u kevin -i newmarket, --ask-sudo-pass
# prompt> ansible-playbook build_docker_image.yml -u ubuntu -i lucerne, --ask-sudo-pass

---

- hosts: all
  vars:
    build_dir: /tmp/podtastic
    name: podtastic
    image: kswope/{{name}}

  tasks:

    # move important stuff into docker build directory
    - synchronize: src=Dockerfile dest={{build_dir}}

    - docker_image: path={{build_dir}} name={{image}} state=present
      sudo: yes


    - shell: docker push {{image}}
      sudo: yes

