# prompt> ansible-playbook build_docker_image.yml -u kevin -i newmarket, --ask-sudo-pass
# prompt> ansible-playbook build_docker_image.yml -u ubuntu -i lucerne, --ask-sudo-pass

---

- hosts: all

  tasks:

    # move important stuff into docker build directory
    - command: cp -r {{clone_dir}}/deploy/Dockerfile                  {{build_dir}}
    - command: cp -r {{clone_dir}}/deploy/nginx/webapp.conf           {{build_dir}}
    - command: cp -r {{clone_dir}}/deploy/nginx/preserve_secrets.conf {{build_dir}}
    - command: cp -r {{clone_dir}}/deploy/nginx/nginx_tunings.conf    {{build_dir}}
    - command: cp -r {{clone_dir}}/deploy/apt_upgrade.txt             {{build_dir}}
    - command: cp -r {{clone_dir}}/deploy/rake_db_migrate.sh          {{build_dir}}
    - command: cp -r {{clone_dir}}/backend                            {{build_dir}}


    - docker_image: path={{build_dir}} name={{image}} tag={{commit}} state=present
      sudo: yes


    - shell: docker push {{image}}:{{commit}}
      sudo: yes

