#!/bin/bash

# Returns true only if the current directory is git commited and push


STAT=`git status --porcelain`
REV=`git rev-list @{u}..` # unpushed

if [ -n "$STAT" ] || [ -n "$REV" ]; then
    echo "returning false!!!!!"
    exit 1
fi


