# prompt> ansible-playbook build_docker_image.yml -u kevin -i newmarket, --ask-sudo-pass
# prompt> ansible-playbook build_docker_image.yml -u ubuntu -i lucerne, --ask-sudo-pass

---

- hosts: all
  vars:
    build_dir: /tmp/podtastic_build/
    name: podtastic
    image: kswope/{{name}}
    repo: https://github.com/kswope/podtastic 

  tasks:

    - local_action: command gitdone

    - file: path='{{build_dir}}' state=directory

    # clone git repo
    # https://developer.github.com/guides/using-ssh-agent-forwarding/
    - git: repo={{repo}} dest={{build_dir}}

    # build image
    - docker_image: path={{build_dir}} name={{image}} state=build
      sudo: yes

    # - shell: docker push {{image}}
    #   sudo: yes

    - docker: 
        image: '{{image}}'
        name:  '{{name}}'
        state: reloaded
        env:
          RDS_USERNAME: "{{ lookup('env','RDS_USERNAME') }}"
          RDS_PASSWORD: "{{ lookup('env','RDS_PASSWORD') }}"
      sudo: yes



